package movie;
// Generated 2017-3-29 22:27:00 by Hibernate Tools 3.5.0.Final

/**
 * FilmList generated by hbm2java
 */
public class FilmList implements java.io.Serializable {

	private FilmListId id;

	public FilmList() {
	}

	public FilmList(FilmListId id) {
		this.id = id;
	}

	public FilmListId getId() {
		return this.id;
	}

	public void setId(FilmListId id) {
		this.id = id;
	}

}
